language: python
sudo: false
python:
  - "2.7"
install:
  - "pip install --upgrade pip"
  - "pip install -r requirements.txt"
  - "python setup.py install"
before_script:
  - "flake8 seleniumbase/*/*.py"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "wget http://chromedriver.googlecode.com/files/chromedriver_linux32_23.0.1240.0.zip"
  - "unzip chromedriver_linux32_23.0.1240.0.zip"
  - "sudo mv chromedriver /usr/bin"
  - "nosetests examples/my_first_test.py --with-selenium --browser=chrome"
env:
  matrix:
  - BROWSER=chrome
notifications:
  email: false
