dist: trusty
sudo: required
language: python
addons:
  firefox: "46.0.1"
python:
  - "2.7"
install:
  - "pip install --upgrade pip"
  - "pip install -r server_requirements.txt"
  - "python server_setup.py install"
  - "sudo rm -f /etc/boto.cfg"
before_script:
  - "flake8 seleniumbase/*.py"
  - "flake8 seleniumbase/*/*.py"
  - "flake8 seleniumbase/*/*/*.py"
  - "flake8 seleniumbase/*/*/*/*.py"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "phantomjs --version"
  - "firefox --version"
script:
  - "pytest examples/my_first_test.py --with-selenium --browser=phantomjs"
  - "pytest examples/my_first_test.py --with-selenium --browser=firefox -s"
notifications:
  email: false
