site_name: SeleniumBase
repo_url: https://github.com/seleniumbase/SeleniumBase/
edit_uri: ""
site_dir: "site"
docs_dir: "docs"
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
theme:
  name: material
  logo: https://cdn2.hubspot.net/hubfs/100006/images/super_square_logo_3.png
  favicon: img/favicon.ico
plugins:
  - search
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: docs.prepare:main
nav:
  - Home: README.md
  - Features: help_docs/features_list.md
  - CMD Options: help_docs/customizing_test_runs.md
  - Mobile Testing: help_docs/mobile_testing.md
  - Examples: examples/ReadMe.md
  - Reports: examples/example_logs/ReadMe.md
  - API: help_docs/method_summary.md
  - Console Scripts: seleniumbase/console_scripts/ReadMe.md
  - Site Tours: examples/tour_examples/ReadMe.md
  - Translations: help_docs/translations.md
  - Recorder: seleniumbase/utilities/selenium_ide/ReadMe.md
  - MasterQA: examples/master_qa/ReadMe.md
  - Visual Testing: examples/visual_testing/ReadMe.md
  - GitHub CI: integrations/github/workflows/ReadMe.md
  - Help Docs: help_docs/ReadMe.md
  - Happy Customers: help_docs/happy_customers.md
  - Hidden Files: help_docs/hidden_files_info.md
  - How it Works: help_docs/how_it_works.md
  - Install SeleniumBase: help_docs/install.md
  - Install Python, pip, and git: help_docs/install_python_pip_git.md
  - MySQL installation: help_docs/mysql_installation.md
  - Safari Driver Tips: help_docs/using_safari_driver.md
  - Verifying WebDriver: help_docs/verify_webdriver.md
  - Virtualenv Instructions: help_docs/virtualenv_instructions.md
  - WebDriver Installation: help_docs/webdriver_installation.md
  - Azure Jenkins: integrations/azure/jenkins/ReadMe.md
  - Docker Help: integrations/docker/ReadMe.md
  - Google Cloud: integrations/google_cloud/ReadMe.md
  - Katalon Integration: integrations/katalon/ReadMe.md
  - Common Decorators: seleniumbase/common/ReadMe.md
  - Master QA: seleniumbase/masterqa/ReadMe.md
  - Selenium Grid: seleniumbase/utilities/selenium_grid/ReadMe.md 
